In [1150]:
import numpy as np
vecs = np.array(list(map(int, np.random.random(300) * 100)))
vecs = np.resize(vecs, (100, 3))
vecs = np.insert(vecs, 3, np.zeros(100), axis=1)

In [1151]:
def rotate_vec(vec, theta=None, i=None, j=None):

    dim = vec.size
    if theta is None:
        theta = 2 * np.pi * np.random.random()

    if i is None:
        i = np.random.choice(dim)
    if j is None:
        j = np.random.choice(dim)
        while i == j:
            j = np.random.choice(dim)
    rotational_matrix = np.identity(dim)
    rotational_matrix[i][i] = rotational_matrix[j][j] = np.cos(theta)
    rotational_matrix[i][j] = np.sin(theta)
    rotational_matrix[j][i] = -np.sin(theta)

    return np.matmul(rotational_matrix, vec), rotational_matrix

In [1152]:
dim = 4
theta = np.pi / 2
i = 0
j = 1

In [1153]:
np.set_printoptions(precision=2)
rotate_vec(vecs[0], theta= 2 * np.pi * np.random.random())

(array([-21.26,  -0.38,  69.  ,   0.  ]),
 array([[-0.76, -0.65,  0.  ,  0.  ],
        [ 0.65, -0.76,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  1.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  1.  ]]))

Making the auto-encoder

In [1162]:
tot_rot = np.identity(4)
for i in range(3):
    _, rotvect = rotate_vec(np.zeros(4))
    tot_rot = np.matmul(rotvect, tot_rot)
    vecs = np.array([np.matmul(rotvect, vec) for vec in vecs])

tot_rot


array([[ 1.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.54,  0.84],
       [ 0.  ,  0.  , -0.84,  0.54]])

In [1282]:
W = np.zeros(4)

In [1283]:
for i in range(1000):
    vec_pred = vecs.dot(W.T)
    dW = - ( 2 *  vecs.T.dot(vecs.T[0] - vec_pred)) / vecs.size
    W -= dW * 0.0001
W, dW

(array([ 1.,  0.,  0., -0.]), array([-0.,  0., -0.,  0.]))

TypeError: list indices must be integers or slices, not tuple

In [1100]:
vec[0], vec_pred

(-50.311557318132564, -50.199010175811225)

In [949]:
def dist_error(vec_pred, vec_real):
    return np.array([(r - p)**2 for p, r in zip(vec_pred, vec_real)])

In [950]:
def dist_error_derivative(vec_pred, vec_real):
    m = len(vec_pred)
    n = len(vec_real)
    grad = np.zeros(m * n).reshape(m, n)
    e = dist_error(vec_pred, vec_real)
    for i, val in enumerate(vec_pred):
        grad[i][i] = 2 * e[i] * val 
    return grad

In [970]:
weights = np.random.random((4, 4))
c = 0
for ep in range(1000):
    for vec in vecs:
        vec_p = np.matmul(vec, weights)
        c += abs(dist_error_derivative(vec_p, vec)[0])
    weights[0] -= np.sqrt(c / len(vecs))
    print(weights[0][0])


-921.0802998496871
-17182394.610147797
-43676116268480.695
-1.7700448720886604e+23
-4.566617854125585e+37
-1.8923883309654484e+59
-5.048166239144249e+91
-2.1994734706976364e+140
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf

C:\Users\joseg\AppData\Local\Temp/ipykernel_4340/10825316.py:7: RuntimeWarning: overflow encountered in double_scalars
  grad[i][i] = 2 * e[i] * val



-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf
-inf

In [952]:
vec = [1, 2, 3, 4]
np.matmul(vec, w)

array([ 80,  90, 100, 110])

In [953]:
dist_error_derivative(vec_p, vec)

array([[ -41849.89,       0.  ,       0.  ,       0.  ],
       [      0.  ,     243.74,       0.  ,       0.  ],
       [      0.  ,       0.  ,   -8875.91,       0.  ],
       [      0.  ,       0.  ,       0.  , -291873.49]])

In [954]:
weights

array([[-20.5 ,   0.11,   0.5 ,   0.96],
       [  0.56, -11.01,   0.41,   0.05],
       [  0.4 ,   0.1 ,    nan,   0.37],
       [  0.62,   0.77,   0.41,    nan]])