In [1]:
from IPython.display import clear_output
import numpy as np

In [342]:
DATA_COUNT = 1000
A_DIM = 5
R_DIM = 1
DATA_LIMIT = 10

Rotation stuffs

In [354]:
# Returns a matrix which could be used to rotate any vector or dimension=dim
def rotate_vec(dim=4, theta=None, i=None, j=None):

    if theta is None:
        theta = 2 * np.pi * np.random.random()

    if i is None:
        i = np.random.choice(dim)

    if j is None:
        j = np.random.choice(dim)
        while i == j:
            j = np.random.choice(dim)

    rotational_matrix = np.identity(dim)
    rotational_matrix[i][i] = rotational_matrix[j][j] = np.cos(theta)
    rotational_matrix[i][j] = np.sin(theta)
    rotational_matrix[j][i] = -np.sin(theta)

    return rotational_matrix


def random_rot(dim, count=10):
    id = np.identity(dim)
    for i in range(count):
        id = id.dot(rotate_vec(dim=dim))
    return id


Creating data

In [82]:


def tensor_diff(a, b):
    c = a - b
    c = np.squeeze(c)
    c_t = np.var(c)
    c = np.square(c)
    c = np.sqrt(np.average(c))
    return np.average(c), c_t, np.exp(- np.average(c)) * 100

def dropout_p_matrix(percent,shp, step = True):
    ch = np.random.random(shp[0])
    d_l = np.vectorize(lambda x : 1 if x < percent else 0)
    x = d_l(ch)
    return np.tile(x, (shp[1], 1)).T

def hyp(vex):
    return vex

In [5]:
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [164]:

def regressutil(weights, training_data, training_label, epochs, testing_data, testing_label,alpha = 0.0001, update_interval = 10, retain = 1):

    for epoch in range(epochs):        
        hidden_layer = training_data.dot(weights[0] * dropout_p_matrix(retain, weights[0].shape))
        predicted_label = hidden_layer.dot(weights[1]* dropout_p_matrix(retain, weights[1].shape))
        error = training_label - predicted_label
        dW0 = - training_data.T.dot(2 * error.dot(weights[1].T)) / training_data.size
        dW1 = - hidden_layer.T.dot(2 * error) / training_data.size
        weights[0] -= dW0 * alpha
        weights[1] -= dW1 * alpha

        if epoch % (epochs // update_interval) == 0:
            clear_output()
            print("Error :", tensor_diff(testing_data.dot(weights[0]).dot(weights[1]), testing_label))
            print("Weight")
            print(weights)
    return weights

        

In [30]:
def regress(W, vecs, vecsy, epochs, initial_dropout = 0.7):
    vecs = np.array(np.split(vecs, 10))
    vecsy = np.array(np.split(vecsy, 10))
    for i in range(10):
        W = regressutil(W, np.vstack(np.delete(vecs, i, axis=0)), np.vstack(np.delete(vecsy, i, axis=0)), epochs //10, vecs[i], vecsy[i], update_interval = 1, retain = initial_dropout)
    
    return W

In [343]:
vecs = (np.random.random((DATA_COUNT, R_DIM)) * 2 * DATA_LIMIT) - DATA_LIMIT
vecs = np.append(vecs, np.zeros((DATA_COUNT, A_DIM - R_DIM)), axis = 1)
print(vecs)
r = random_rot(A_DIM, count=4)
vecs = vecs.dot(r)
vecsy = vecs
vecs

[[-5.1384  0.      0.      0.      0.    ]
 [-3.39    0.      0.      0.      0.    ]
 [-9.8789  0.      0.      0.      0.    ]
 ...
 [ 7.7516  0.      0.      0.      0.    ]
 [-4.6443  0.      0.      0.      0.    ]
 [ 7.354   0.      0.      0.      0.    ]]


array([[ 0.0009,  0.5833, -1.1484, -4.7292,  1.5423],
       [ 0.0006,  0.3848, -0.7576, -3.1201,  1.0175],
       [ 0.0017,  1.1215, -2.2078, -9.0922,  2.9652],
       ...,
       [-0.0013, -0.88  ,  1.7324,  7.1344, -2.3267],
       [ 0.0008,  0.5272, -1.0379, -4.2744,  1.394 ],
       [-0.0012, -0.8348,  1.6435,  6.7684, -2.2074]])

In [331]:
# With noise
vecs = (np.random.random((DATA_COUNT, R_DIM)) * 2 * DATA_LIMIT) - DATA_LIMIT
vecs = np.append(vecs, np.random.random((DATA_COUNT, A_DIM - R_DIM)), axis = 1)
r = random_rot(A_DIM, count=2)
vecs = vecs.dot(r)
vecsy = vecs
vecs

array([[ 3.8079, -7.0115, -4.2212,  1.6509,  0.8425],
       [-5.0738,  9.5803, -5.6131, -6.4801,  0.7834],
       [ 3.2861, -5.0211, -0.1428,  2.9094,  0.1641],
       ...,
       [-2.4358,  7.6912,  4.6555,  1.0831,  0.4899],
       [-0.2038,  4.6031, -1.4049, -0.5252,  0.1852],
       [-9.4161,  3.6658,  3.6146, -4.8746,  0.3573]])

In [344]:
#W = np.array([np.delete(np.identity(DIM + 1), DIM, 1), np.delete(np.identity(DIM + 1), DIM, 0)])
W = np.array([np.random.random((A_DIM, R_DIM)), np.random.random((R_DIM, A_DIM))])
W

C:\Users\joseg\AppData\Local\Temp/ipykernel_14656/966831837.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  W = np.array([np.random.random((A_DIM, R_DIM)), np.random.random((R_DIM, A_DIM))])


array([array([[0.1627],
              [0.1459],
              [0.9503],
              [0.9387],
              [0.2511]]),
       array([[0.3667, 0.6606, 0.1518, 0.8345, 0.8057]])], dtype=object)

In [351]:
W = regress(W, vecs, vecsy, 8000, initial_dropout=0.95)
W

Error : (0.544465624921398, 0.2962812095191002, 58.01517191420042)
Weight
[array([[ 0.1606],
        [-1.2342],
        [ 3.6671],
        [12.1271],
        [-3.3978]]) array([[-0.    , -0.0104,  0.0205,  0.0845, -0.0276]])]


array([array([[ 0.1606],
              [-1.2345],
              [ 3.6678],
              [12.1298],
              [-3.3987]]),
       array([[-0.    , -0.0086,  0.017 ,  0.07  , -0.0228]])],
      dtype=object)

In [352]:
v1 = (np.random.random((DATA_COUNT, R_DIM)) * DATA_LIMIT) - DATA_LIMIT
v1 = np.append(v1, np.random.random((DATA_COUNT, A_DIM - R_DIM)), axis = 1)
v1 = v1.dot(r)
print(tensor_diff(vecs.dot(W[0]).dot(W[1]), vecs))
tensor_diff(v1.dot(W[0]).dot(W[1]), v1)

(0.00017198727834848114, 2.9579275985618358e-08, 99.98280275106156)


(0.5188906110636123, 0.26203364896044595, 59.51804684751384)

In [319]:
l = np.array([[3, 4, 5, 6]])
m = np.array([[3, 4, 4, 5], [4, 4, 5, 2]])
np.append(l, m, axis=0)

array([[3, 4, 5, 6],
       [3, 4, 4, 5],
       [4, 4, 5, 2]])