In [115]:
import numpy as np
vecs = list(map(int, np.random.random(300) * 100))
vecs = np.resize(vecs, (100, 3))
vecs = np.insert(vecs, 3, np.random.random(100) * 10, axis=1)

In [116]:
theta = np.pi / 2
i = 0
j = 1
rotational_matrix = np.identity(4)
rotational_matrix[i][i] = rotational_matrix[j][j] = np.cos(theta)
rotational_matrix[i][j] = np.sin(theta)
rotational_matrix[j][i] = -np.sin(theta)
rotational_matrix

array([[ 6.12e-17,  1.00e+00,  0.00e+00,  0.00e+00],
       [-1.00e+00,  6.12e-17,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  0.00e+00,  1.00e+00]])

In [117]:
vecs[0]

array([39, 49, 42,  6])

In [118]:
np.set_printoptions(precision=2)
np.matmul(rotational_matrix, vecs[0])

array([ 49., -39.,  42.,   6.])